### ISSUE TITLE
`docopt` does not compile with latest `devel` branch of the Nim compiler

### ISSUE THREAD

**Issue by ziotom78** [docopt/docopt.nim#11]
I am having problems compiling an application using `docopt` and the latest `devel` branch of the Nim compiler. The problem can be reproduced by simply trying to compile `docopt.nim` itself:

`````
home/tomasi/.nimble/pkgs/docopt-0.6.1/docopt.nim(131, 15) Error: type mismatch: got (seq[seq[Pattern]])
but expected one of: 
system.delete(x: var seq[T], i: Natural)
sequtils.delete(s: var seq[T], first: Natural, last: Natural)
strutils.delete(s: var string, first: int, last: int)
`````

(plus, a lot of "Regexp is deprecated" warning are produced).

**Comment by BlaXpirit** [comment]
Fixed in https://github.com/docopt/docopt.nim/pull/9

**Comment by ziotom78** [comment]
Thanks. Any plan to tag a new release? Currently `nimble install docopt` installs version 0.6.1, which still does not compile. (I had to run `nimble install docopt@#head` to get the latest version.)

**Comment by BlaXpirit** [comment]
Also fixed `re` deprecations.
https://github.com/docopt/docopt.nim/commit/0aaf814d3c884f83d7d0b232192a4e9dba9a73d2

Planning to release after Nim's next release.

**Comment by BlaXpirit** [comment]
I made a release some time ago, forgot to mention here.
